import React, { useState } from 'react';
import { Sparkles, User, ArrowRight, Play, Copy, Check, Cpu } from 'lucide-react';
import SafeMarkdown from './SafeMarkdown.jsx';

export default function HelperMessage({ message, onLaunchResearch, isLaunchingResearch }) {
  const isUser = message.role === 'user';
  const isHelper = message.role === 'assistant';
  const [copied, setCopied] = useState(false);

  const handleCopyMessage = async () => {
    if (!message.content) return;
    try {
      await navigator.clipboard.writeText(message.content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy response', err);
    }
  };

  const getProviderBadgeLabel = (provider) => {
    if (!provider) return null;
    if (provider.includes('openai')) return 'OpenAI';
    if (provider.includes('gemini')) return 'Gemini';
    if (provider.includes('groq')) return 'Groq';
    if (provider.includes('neural')) return 'Neural AI';
    if (provider.includes('contextual') || provider.includes('knowledge')) return 'Built-in AI';
    return null;
  };

  const providerLabel = !isUser ? getProviderBadgeLabel(message.provider) : null;

  return (
    <div className={`helper-message-row ${isUser ? 'helper-message-user' : 'helper-message-assistant'}`}>
      <div className="helper-avatar">
        {isUser ? (
          <div className="helper-avatar-user" title="You">
            <User size={14} />
          </div>
        ) : (
          <div className="helper-avatar-helper" title="Helper AI Assistant">
            <Sparkles size={14} />
          </div>
        )}
      </div>

      <div className="helper-message-bubble-wrapper">
        <div className="helper-message-header">
          <div className="helper-header-meta">
            <span className="helper-sender-name">
              {isUser ? 'You' : '✨ Helper'}
            </span>
            {providerLabel && (
              <span className="helper-engine-tag" title={`Generated by ${providerLabel}`}>
                <Cpu size={10} style={{ display: 'inline', marginRight: '2px' }} />
                {providerLabel}
              </span>
            )}
          </div>

          <div className="helper-header-tools">
            {message.timestamp && (
              <span className="helper-message-time">
                {new Date(message.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
              </span>
            )}

            {!isUser && message.content && (
              <button
                type="button"
                className="helper-msg-copy-btn"
                onClick={handleCopyMessage}
                title={copied ? 'Copied!' : 'Copy response'}
                aria-label="Copy message"
              >
                {copied ? <Check size={12} style={{ color: 'var(--accent-emerald)' }} /> : <Copy size={12} />}
              </button>
            )}
          </div>
        </div>

        <div className="helper-message-content">
          <SafeMarkdown content={message.content} />

          {/* Research Pipeline Action Card if message is identified as an empirical research query */}
          {message.isResearchTopic && message.suggestedTopic && (
            <div className="helper-research-action-card">
              <div className="helper-research-action-header">
                <span className="helper-research-badge">
                  <Play size={11} fill="currentColor" /> Autonomous Research Workflow
                </span>
              </div>
              <div className="helper-research-action-topic">
                <strong>Topic:</strong> "{message.suggestedTopic}"
              </div>
              <p className="helper-research-action-desc">
                Our 6 coordinated agents will decompose this topic, search authentic web sources, extract empirical facts, and validate citations with zero fabrication.
              </p>
              <button
                type="button"
                className="helper-launch-research-btn"
                onClick={() => onLaunchResearch(message.suggestedTopic)}
                disabled={isLaunchingResearch}
              >
                {isLaunchingResearch ? (
                  <>
                    <span className="helper-spinner-inline" />
                    <span>Launching Pipeline...</span>
                  </>
                ) : (
                  <>
                    <span>🚀 Launch Deep Research</span>
                    <ArrowRight size={14} />
                  </>
                )}
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
